services:
  - type: web
    name: entellistore-backend
    env: node
    plan: free
    buildCommand: npm install --include=dev --no-audit && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
